# fly.toml app configuration file generated for backend-wall-street on 2025-06-20T23:36:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-wall-street'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
